/**
 * Environment file writer for the setup wizard.
 * Reads the existing .env, merges new values, writes back.
 * Preserves comments and structure.
 */

import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';

const ENV_PATH = resolve(process.cwd(), '.env');

interface EnvUpdate {
  [key: string]: string | undefined; // undefined = remove
}

/**
 * Read the current .env file as a map
 */
export async function readEnvFile(): Promise<Map<string, string>> {
  try {
    const content = await readFile(ENV_PATH, 'utf-8');
    const map = new Map<string, string>();
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx > 0) {
        const key = trimmed.slice(0, eqIdx).trim();
        const value = trimmed.slice(eqIdx + 1).trim();
        map.set(key, value);
      }
    }
    return map;
  } catch {
    return new Map();
  }
}

/**
 * Update the .env file, preserving existing comments and structure.
 * New keys are appended at the end in a setup section.
 * Existing keys are updated in-place.
 */
export async function updateEnvFile(updates: EnvUpdate): Promise<{
  success: boolean;
  path: string;
  updated: string[];
  added: string[];
}> {
  let content: string;
  try {
    content = await readFile(ENV_PATH, 'utf-8');
  } catch {
    content = '# Exprsn Configuration\n# Generated by setup wizard\n\n';
  }

  const lines = content.split('\n');
  const updatedKeys: string[] = [];
  const addedKeys: string[] = [];
  const handled = new Set<string>();

  // Update existing keys in-place
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx <= 0) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    if (key in updates) {
      const newValue = updates[key];
      if (newValue !== undefined) {
        lines[i] = `${key}=${newValue}`;
        updatedKeys.push(key);
      }
      handled.add(key);
    }
  }

  // Append new keys that weren't found in the file
  const newKeys = Object.entries(updates).filter(
    ([key, value]) => !handled.has(key) && value !== undefined,
  );

  if (newKeys.length > 0) {
    // Check if there's already a setup section
    const hasSetupSection = lines.some((l) => l.includes('Setup Wizard Configuration'));

    if (!hasSetupSection) {
      lines.push('');
      lines.push('# ==============================================');
      lines.push('# Setup Wizard Configuration');
      lines.push('# ==============================================');
    }

    for (const [key, value] of newKeys) {
      lines.push(`${key}=${value}`);
      addedKeys.push(key);
    }
  }

  await writeFile(ENV_PATH, lines.join('\n'));

  return { success: true, path: ENV_PATH, updated: updatedKeys, added: addedKeys };
}

/**
 * Get all env vars that the setup wizard should capture
 */
export function getSetupEnvSchema(): Array<{
  key: string;
  label: string;
  category: string;
  required: boolean;
  default?: string;
  description: string;
  sensitive?: boolean;
}> {
  return [
    // Server
    {
      key: 'PORT',
      label: 'API Port',
      category: 'server',
      required: true,
      default: '3000',
      description: 'Port the API server listens on',
    },
    {
      key: 'HOST',
      label: 'Host',
      category: 'server',
      required: true,
      default: '0.0.0.0',
      description: 'Host to bind to',
    },
    {
      key: 'APP_URL',
      label: 'App URL',
      category: 'server',
      required: true,
      default: 'http://localhost:3000',
      description: 'Public URL of the application',
    },
    {
      key: 'NODE_ENV',
      label: 'Environment',
      category: 'server',
      required: true,
      default: 'production',
      description: 'production, development, or test',
    },

    // Branding
    {
      key: 'PLATFORM_NAME',
      label: 'Platform Name',
      category: 'branding',
      required: false,
      default: 'Exprsn',
      description: 'Name shown in the UI',
    },
    {
      key: 'PLATFORM_ACCENT_COLOR',
      label: 'Accent Color',
      category: 'branding',
      required: false,
      default: '#f83b85',
      description: 'Primary accent color (hex)',
    },

    // Database
    {
      key: 'DATABASE_URL',
      label: 'Database URL',
      category: 'database',
      required: true,
      description: 'PostgreSQL connection string',
      sensitive: true,
    },

    // Redis
    {
      key: 'REDIS_URL',
      label: 'Redis URL',
      category: 'redis',
      required: false,
      default: 'redis://localhost:6379',
      description: 'Redis connection string',
    },

    // Storage
    {
      key: 'DO_SPACES_ENDPOINT',
      label: 'S3 Endpoint',
      category: 'storage',
      required: false,
      description: 'S3-compatible endpoint URL',
    },
    {
      key: 'DO_SPACES_KEY',
      label: 'S3 Access Key',
      category: 'storage',
      required: false,
      description: 'S3 access key',
      sensitive: true,
    },
    {
      key: 'DO_SPACES_SECRET',
      label: 'S3 Secret Key',
      category: 'storage',
      required: false,
      description: 'S3 secret key',
      sensitive: true,
    },
    {
      key: 'DO_SPACES_BUCKET',
      label: 'S3 Bucket',
      category: 'storage',
      required: false,
      default: 'exprsn-uploads',
      description: 'S3 bucket name',
    },
    {
      key: 'DO_SPACES_CDN',
      label: 'CDN URL',
      category: 'storage',
      required: false,
      description: 'CDN base URL for media',
    },

    // Email
    {
      key: 'SMTP_HOST',
      label: 'SMTP Host',
      category: 'email',
      required: false,
      description: 'SMTP server hostname',
    },
    {
      key: 'SMTP_PORT',
      label: 'SMTP Port',
      category: 'email',
      required: false,
      default: '587',
      description: 'SMTP server port',
    },
    {
      key: 'SMTP_USER',
      label: 'SMTP User',
      category: 'email',
      required: false,
      description: 'SMTP username',
      sensitive: true,
    },
    {
      key: 'SMTP_PASS',
      label: 'SMTP Password',
      category: 'email',
      required: false,
      description: 'SMTP password',
      sensitive: true,
    },
    {
      key: 'SMTP_SECURE',
      label: 'SMTP TLS',
      category: 'email',
      required: false,
      default: 'true',
      description: 'Use TLS for SMTP',
    },
    {
      key: 'EMAIL_FROM',
      label: 'From Address',
      category: 'email',
      required: false,
      default: 'noreply@exprsn.app',
      description: 'Sender email address',
    },

    // Security
    {
      key: 'JWT_SECRET',
      label: 'JWT Secret',
      category: 'security',
      required: true,
      description: '64-char random secret for sessions',
      sensitive: true,
    },
    {
      key: 'ENCRYPTION_KEY',
      label: 'Encryption Key',
      category: 'security',
      required: true,
      description: '32+ char key for data encryption',
      sensitive: true,
    },

    // Federation
    {
      key: 'PDS_ENABLED',
      label: 'PDS Enabled',
      category: 'federation',
      required: false,
      default: 'true',
      description: 'Enable AT Protocol PDS',
    },
    {
      key: 'RELAY_ENABLED',
      label: 'Relay Enabled',
      category: 'federation',
      required: false,
      default: 'false',
      description: 'Enable firehose relay',
    },
    {
      key: 'PLC_URL',
      label: 'PLC Directory',
      category: 'federation',
      required: false,
      default: 'https://plc.directory',
      description: 'PLC directory URL',
    },
    {
      key: 'SERVICE_DID',
      label: 'Service DID',
      category: 'federation',
      required: false,
      description: 'Platform service DID',
    },

    // Services
    {
      key: 'PREFETCH_PRODUCER_ENABLED',
      label: 'Prefetch',
      category: 'services',
      required: false,
      default: 'true',
      description: 'Enable prefetch engine',
    },
    {
      key: 'TRANSCODE_WORKER_ENABLED',
      label: 'Transcode Worker',
      category: 'services',
      required: false,
      default: 'true',
      description: 'Enable video transcoding',
    },
    {
      key: 'RENDER_ENABLED',
      label: 'Render Pipeline',
      category: 'services',
      required: false,
      default: 'true',
      description: 'Enable render pipeline',
    },

    // Auth
    {
      key: 'DEV_AUTH_BYPASS',
      label: 'Dev Auth Bypass',
      category: 'auth',
      required: false,
      default: 'false',
      description: 'Bypass auth in development (NEVER in production)',
    },
  ];
}
