/**
 * Core env file generator.
 */

import { ENV_SCHEMA, type Environment, type EnvCategory, createEnvValidationSchema } from './schema.js';
import { generateSecret } from './secrets.js';

export interface GenerateEnvOptions {
  /** Target environment */
  environment: Environment;
  /** Auto-generate secrets for vars with a generator defined */
  autoSecrets?: boolean;
  /** Override values (takes precedence over defaults and auto-secrets) */
  overrides?: Record<string, string>;
  /** Only include these categories (by name). If omitted, all are included. */
  categories?: string[];
  /** Include comment headers for each category */
  comments?: boolean;
}

export interface GenerateEnvResult {
  content: string;
  vars: Map<string, string>;
  generated: string[];
  warnings: string[];
}

/**
 * Generate env file content for a given environment.
 */
export function generateEnvFile(options: GenerateEnvOptions): GenerateEnvResult {
  const {
    environment,
    autoSecrets = false,
    overrides = {},
    categories,
    comments = true,
  } = options;

  const vars = new Map<string, string>();
  const generated: string[] = [];
  const warnings: string[] = [];
  const lines: string[] = [];

  // Load template overrides
  let templateOverrides: Record<string, string> = {};
  if (environment === 'development') {
    templateOverrides = { NODE_ENV: 'development', DEV_AUTH_BYPASS: 'true', LOG_LEVEL: 'debug', SMTP_PORT: '1025', SMTP_SECURE: 'false', BLOB_STORAGE_TYPE: 'local', RELAY_ENABLED: 'false', FEDERATION_CONSUMER_ENABLED: 'false' };
  } else if (environment === 'staging') {
    templateOverrides = { NODE_ENV: 'staging', DEV_AUTH_BYPASS: 'false', LOG_LEVEL: 'info', SMTP_SECURE: 'true', SMTP_PORT: '587', BLOB_STORAGE_TYPE: 's3', RELAY_ENABLED: 'true', FEDERATION_CONSUMER_ENABLED: 'true', TLS_ENABLED: 'true' };
  } else if (environment === 'production') {
    templateOverrides = { NODE_ENV: 'production', DEV_AUTH_BYPASS: 'false', LOG_LEVEL: 'warn', SMTP_SECURE: 'true', SMTP_PORT: '587', BLOB_STORAGE_TYPE: 's3', RELAY_ENABLED: 'true', FEDERATION_CONSUMER_ENABLED: 'true', TLS_ENABLED: 'true', CA_AUTO_BOOTSTRAP: 'false' };
  }

  if (comments) {
    lines.push('# ==============================================');
    lines.push(`# Exprsn ${environment.charAt(0).toUpperCase() + environment.slice(1)} Environment Configuration`);
    lines.push(`# Generated by @exprsn/env-generator`);
    lines.push('# ==============================================');
    lines.push('');
  }

  const filteredCategories: EnvCategory[] = categories
    ? ENV_SCHEMA.filter((c) => categories.includes(c.name))
    : ENV_SCHEMA;

  for (const cat of filteredCategories) {
    if (comments) {
      lines.push(`# ${cat.label}`);
    }

    for (const v of cat.vars) {
      let value: string | undefined;

      // Priority: explicit overrides > template overrides > schema defaults > auto-generate
      if (overrides[v.key] !== undefined) {
        value = overrides[v.key];
      } else if (templateOverrides[v.key] !== undefined) {
        value = templateOverrides[v.key];
      } else if (v.defaults?.[environment] !== undefined) {
        value = v.defaults[environment];
      } else if (autoSecrets && v.generator) {
        value = generateSecret(v.generator);
        generated.push(v.key);
      }

      if (value !== undefined) {
        vars.set(v.key, value);
        lines.push(`${v.key}=${value}`);
      } else if (v.sensitive) {
        // Sensitive vars without a value — add as comment placeholder
        lines.push(`# ${v.key}=`);
        if (environment === 'production') {
          warnings.push(`${v.key}: sensitive variable not set (required for production)`);
        }
      } else {
        lines.push(`# ${v.key}=`);
      }
    }

    if (comments) {
      lines.push('');
    }
  }

  return {
    content: lines.join('\n'),
    vars,
    generated,
    warnings,
  };
}

/**
 * Validate an env file's contents against the schema.
 */
export function validateEnv(
  env: Record<string, string>,
  environment: Environment
): { valid: boolean; errors: string[] } {
  const schema = createEnvValidationSchema(environment);
  const result = schema.safeParse(env);
  if (result.success) {
    return { valid: true, errors: [] };
  }
  const errors = result.error.issues.map(
    (i) => `${i.path.join('.')}: ${i.message}`
  );
  return { valid: false, errors };
}
